In [2]:
import numpy as np
marks = np.array([90,80,70])
print("The mean is :",marks.mean())

The mean is : 80.0


In [3]:
marks = np.array([90, 85, 78, 92, 88])

marks

array([90, 85, 78, 92, 88])

In [4]:
print("Shape:", marks.shape)

print("Dimensions:", marks.ndim)

print("Data Type:", marks.dtype)


Shape: (5,)
Dimensions: 1
Data Type: int64


In [6]:
print(marks + 10)
     

print(marks * 2)


[100  95  88 102  98]
[180 170 156 184 176]


In [7]:
print(marks[1:4])

[85 78 92]


In [8]:
numbers = np.array([1, 2, 3, 4, 5, 6])

matrix = numbers.reshape(2, 3)

matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
print(matrix[0])

print(matrix[1,2])

[1 2 3]
6


In [2]:
#Lets learn numpy by myself
import numpy as np

marks = np.array([100,80,89,92,100])
print("Marks = ",marks)
print("Average = ",np.mean(marks))
print("Maximum = ",np.max(marks))
print("Minimum = ",np.min(marks))

Marks =  [100  80  89  92 100]
Average =  92.2
Maximum =  100
Minimum =  80


In [3]:
#Temperatures
import numpy as np

temps = np.array([32,34,31,30,36])

print ("Average Temperature is :", np.mean(temps))
print ("hottest temp is :",np.max(temps))
print("coldest temp is :",np.min(temps))

Average Temperature is : 32.6
hottest temp is : 36
coldest temp is : 30


In [5]:
prices = np.array([99, 149, 199, 249])

gst = prices*1.18
print ("The cost after gst is :",gst)

The cost after gst is : [116.82 175.82 234.82 293.82]
