In [2]:
import numpy as np
marks = np.array([90,80,70])
print("The mean is :",marks.mean())

The mean is : 80.0


In [3]:
marks = np.array([90, 85, 78, 92, 88])

marks

array([90, 85, 78, 92, 88])

In [4]:
print("Shape:", marks.shape)

print("Dimensions:", marks.ndim)

print("Data Type:", marks.dtype)


Shape: (5,)
Dimensions: 1
Data Type: int64


In [6]:
print(marks + 10)
     

print(marks * 2)


[100  95  88 102  98]
[180 170 156 184 176]


In [7]:
print(marks[1:4])

[85 78 92]


In [8]:
numbers = np.array([1, 2, 3, 4, 5, 6])

matrix = numbers.reshape(2, 3)

matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
print(matrix[0])

print(matrix[1,2])

[1 2 3]
6
